# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, override|
	aws.access_key_id = "AKIAJWALRVMX642FUY6Q"
	aws.secret_access_key = "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"

	aws.ami = "ami-7747d01e"
	aws.keypair_name = "peewee"

	override.ssh.username = "ubuntu"
	override.ssh.private_key_path = "/Users/jayj/.ssh/peewee.pem"

  end
end
